// scripts/uploader.ts
import { google } from 'googleapis';
import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';

const CREDENTIALS_PATH = path.join(process.cwd(), 'client_secret.json');
const TOKEN_PATH = path.join(process.cwd(), 'tokens.json');
const STATE_FILE = 'data/state.json';

export async function uploadVideoToYoutube(videoId: string) {
    console.log(chalk.blue(`🚀 유튜브 업로드 시작 (ID: ${videoId})...`));

    // 1. 영상 정보 찾기
    const state = await fs.readJSON(STATE_FILE);
    const videoItem = state.find((item: any) => item.id === videoId);

    if (!videoItem) {
        console.error('❌ 데이터를 찾을 수 없습니다.');
        return false;
    }

    // 업로드할 파일 경로 결정
    // 1순위: finalVideoPath (렌더링된 결과물)
    // 2순위: out 폴더의 예상 경로 (fallback)
    let uploadFilePath = '';

    if (videoItem.finalVideoPath) {
        uploadFilePath = path.join(process.cwd(), videoItem.finalVideoPath);
    } else {
        // 혹시 finalVideoPath가 기록되지 않았을 경우를 대비
        uploadFilePath = path.join(process.cwd(), 'out', `${videoId}.mp4`);
    }

    if (!fs.existsSync(uploadFilePath)) {
        console.error(chalk.red(`❌ 영상 파일을 찾을 수 없습니다: ${uploadFilePath}`));
        // 혹시 모르니 원본(배경)이라도 업로드 할지? -> 아니오, 렌더링 안된건 의미 없음.
        return false;
    }

    // 2. 인증 설정
    const creds = await fs.readJSON(CREDENTIALS_PATH);
    const tokens = await fs.readJSON(TOKEN_PATH);
    const { client_secret, client_id, redirect_uris } = creds.installed || creds.web;
    const auth = new google.auth.OAuth2(client_id, client_secret, redirect_uris[0]);
    auth.setCredentials(tokens);

    const youtube = google.youtube({ version: 'v3', auth });

    try {
        // 3. 업로드 실행
        console.log(chalk.gray(`   파일 읽는 중: ${uploadFilePath}`));

        const res = await youtube.videos.insert({
            part: ['snippet', 'status'],
            requestBody: {
                snippet: {
                    title: `${videoItem.props.title} #Shorts`,
                    description: `${videoItem.props.subtitle}\n\nGenerated by Clawdbot`,
                    tags: ['Shorts', 'AI', 'Automation', 'Marketing'],
                },
                status: {
                    privacyStatus: 'public',
                    selfDeclaredMadeForKids: false,
                },
            },
            media: {
                body: fs.createReadStream(uploadFilePath),
            },
        });

        console.log(chalk.green(`✅ 업로드 성공! URL: https://youtu.be/${res.data.id}`));

        // 상태 업데이트
        videoItem.status = 'uploaded';
        videoItem.platformId = res.data.id;

        // 중요: 변경된 상태 저장
        await fs.writeJSON(STATE_FILE, state, { spaces: 2 });

        return res.data.id;
    } catch (error: any) {
        console.error('❌ 업로드 실패:', error.message);
        if (error.response) {
            console.error('   Details:', error.response.data);
        }
        return false;
    }
}